import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { basePhotoData, garmentImageData } = await req.json();
    const hfToken = process.env.HF_API_TOKEN;
    const geminiKey = process.env.GEMINI_API_KEY;

    if (!basePhotoData || !garmentImageData) {
      return NextResponse.json({ error: 'Both person and garment images are required' }, { status: 400 });
    }

    const parseDataUrl = (dataUrl: string | null) => {
      if (!dataUrl) return null;
      const match = dataUrl.trim().match(/^data:([^;]+);base64,([\s\S]+)$/);
      if (!match) return null;
      return { mimeType: match[1], data: match[2].trim() };
    };

    const baseImg = parseDataUrl(basePhotoData);
    const garmentImg = parseDataUrl(garmentImageData);

    if (!baseImg) return NextResponse.json({ result: basePhotoData, isFallback: true, engine: "Fallback", message: "Invalid person photo format." });
    if (!garmentImg) return NextResponse.json({ result: basePhotoData, isFallback: true, engine: "Fallback", message: "Invalid garment image format." });

    // ───── ENGINE A: Hugging Face IDM-VTON (Best Specialized Try-On) ─────
    if (hfToken) {
      console.log("[Try-On] Attempting HF IDM-VTON...");
      try {
        const hfResp = await fetch(
          "https://router.huggingface.co/hf-inference/models/yisol/IDM-VTON",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${hfToken}`,
              "Content-Type": "application/json",
              "x-wait-for-model": "true"
            },
            body: JSON.stringify({
              inputs: {
                background: `data:${baseImg.mimeType};base64,${baseImg.data}`,
                garment: `data:${garmentImg.mimeType};base64,${garmentImg.data}`
              }
            }),
            signal: AbortSignal.timeout(35000)
          }
        );
        if (hfResp.ok) {
          const contentType = hfResp.headers.get("content-type") || "image/png";
          const buf = await hfResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          return NextResponse.json({
            result: `data:${contentType};base64,${b64}`,
            engine: "AI Virtual Try-On", isFallback: false,
            message: "Your virtual look has been generated by AI."
          });
        }
      } catch (hfErr) {
        console.warn("[Try-On] HF failed:", hfErr);
      }
    }

    // ───── ENGINE B: Gemini Direct Multi-Image Edit (HIGH FIDELITY) ─────
    // Pass BOTH images directly — no text conversion — so the exact
    // garment texture, color, logo, and design are preserved visually.
    if (geminiKey) {
      console.log("[Try-On] Attempting Gemini direct multi-image edit...");
      try {
        const editResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  {
                    text: `Image editing task:
- Image 1 is a PERSON photo.
- Image 2 is a CLOTHING GARMENT (product photo).

Your task: Produce a realistic edited version of Image 1 where the person is wearing the EXACT clothing from Image 2. 
Rules:
1. The garment must match Image 2 in every visual detail: exact color shade, fabric texture, pattern, collar style, buttons, logo/embroidery, pockets, sleeve length.
2. Keep the person's face, hair, skin tone, build, pose, expression, and background 100% identical to Image 1.
3. Only the clothing/shirt region should change. Nothing else.
4. Make the result look like a natural, realistic photo — not illustrated.`
                  },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }],
              generationConfig: { responseModalities: ["IMAGE", "TEXT"] }
            }),
            signal: AbortSignal.timeout(45000)
          }
        );

        if (editResp.ok) {
          const editData = await editResp.json();
          const imgPart = editData.candidates?.[0]?.content?.parts?.find(
            (p: { inlineData?: { data: string; mimeType: string } }) => p.inlineData
          );
          if (imgPart?.inlineData?.data) {
            console.log("[Try-On] Gemini multi-image edit success!");
            return NextResponse.json({
              result: `data:${imgPart.inlineData.mimeType || "image/png"};base64,${imgPart.inlineData.data}`,
              engine: "Gemini Image Edit",
              isFallback: false,
              message: "✨ AI Try-On: Your photo with the garment edited in. See how it fits!"
            });
          } else {
            const textPart = editData.candidates?.[0]?.content?.parts?.find(
              (p: { text?: string }) => p.text
            );
            console.warn("[Try-On] Gemini multi-image: no image returned. Reason:", textPart?.text?.slice(0, 150));
          }
        } else {
          const errText = await editResp.text().catch(() => "");
          console.warn("[Try-On] Gemini multi-image failed:", editResp.status, errText.slice(0, 200));
        }
      } catch (gemErr) {
        console.warn("[Try-On] Gemini multi-image error:", gemErr);
      }
    }

    // ───── ENGINE C: Gemini Single-Image Edit (garment described from product image) ─────
    // Fallback: describe garment in very high detail, then edit single person photo
    if (geminiKey) {
      console.log("[Try-On] Falling back to single-image Gemini edit...");
      try {
        // Describe the garment with maximum visual fidelity
        const descResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  { text: "Describe this clothing item in extreme detail for an image editor. Include: exact color (e.g. heathered forest green, not just 'green'), fabric texture and weave pattern, fit style, collar type, button style/color, sleeve length, any visible logos/emblems/embroidery (describe size, position, color, and design), chest pockets, cuffs. Be very precise." },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }]
            }),
            signal: AbortSignal.timeout(12000)
          }
        );

        let garmentDescription = "a casual button-down shirt";
        if (descResp.ok) {
          const descData = await descResp.json();
          garmentDescription = descData.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || garmentDescription;
          console.log("[Try-On] Garment desc:", garmentDescription.slice(0, 100));
        }

        const editResp2 = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  {
                    text: `Image editing task: Keep this person's face, hair, body shape, skin tone, pose, and background EXACTLY the same. Replace ONLY the shirt/top they are wearing with this garment: ${garmentDescription}. Match every visual detail described. Make it look photorealistic.`
                  },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } }
                ]
              }],
              generationConfig: { responseModalities: ["IMAGE", "TEXT"] }
            }),
            signal: AbortSignal.timeout(35000)
          }
        );

        if (editResp2.ok) {
          const editData2 = await editResp2.json();
          const imgPart2 = editData2.candidates?.[0]?.content?.parts?.find(
            (p: { inlineData?: { data: string; mimeType: string } }) => p.inlineData
          );
          if (imgPart2?.inlineData?.data) {
            return NextResponse.json({
              result: `data:${imgPart2.inlineData.mimeType || "image/png"};base64,${imgPart2.inlineData.data}`,
              engine: "Gemini Image Edit",
              isFallback: false,
              message: `✨ AI Try-On: ${garmentDescription.slice(0, 80)}...`
            });
          }
        }
      } catch (editErr) {
        console.warn("[Try-On] Single-image edit error:", editErr);
      }
    }

    // ───── ENGINE D: Gemini Stylist (text only, last resort) ─────
    if (geminiKey) {
      try {
        const geminiResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  { text: "In 2 sentences: how would this exact clothing item look on this person? Mention fit, color contrast, and style." },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }]
            }),
            signal: AbortSignal.timeout(10000)
          }
        );
        if (geminiResp.ok) {
          const gemData = await geminiResp.json();
          const note = gemData.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
          return NextResponse.json({
            result: basePhotoData,
            engine: "Gemini Stylist", isFallback: true,
            message: note ? `✨ AI Style Analysis: ${note}` : "AI engines are busy. Showing your photo."
          });
        }
      } catch { /* silent */ }
    }

    return NextResponse.json({
      result: basePhotoData,
      engine: "Preview Mode", isFallback: true,
      message: "AI engines are warming up. Try again in a moment."
    });

  } catch (err: unknown) {
    console.error("[Try-On] Critical error:", err);
    return NextResponse.json({ error: "Failed to process try-on" }, { status: 500 });
  }
}
