import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { basePhotoData, garmentImageData } = await req.json();
    const hfToken = process.env.HF_API_TOKEN;
    const geminiKey = process.env.GEMINI_API_KEY;

    if (!basePhotoData || !garmentImageData) {
      return NextResponse.json({ error: 'Both person and garment images are required' }, { status: 400 });
    }

    // Helper: extract the raw base64 bytes + mime type from a data URL
    const parseDataUrl = (dataUrl: string | null) => {
      if (!dataUrl) return null;
      const trimmed = dataUrl.trim();
      const match = trimmed.match(/^data:([^;]+);base64,([\s\S]+)$/);
      if (!match) return null;
      return { mimeType: match[1], data: match[2].trim() };
    };

    const baseImg = parseDataUrl(basePhotoData);
    const garmentImg = parseDataUrl(garmentImageData);

    if (!baseImg) {
      return NextResponse.json({ result: basePhotoData, isFallback: true, engine: "Fallback", message: "Invalid person photo format." });
    }
    if (!garmentImg) {
      return NextResponse.json({ result: basePhotoData, isFallback: true, engine: "Fallback", message: "Invalid garment image format." });
    }

    // ───── ENGINE A: Hugging Face IDM-VTON (Specialized Try-On) ─────
    if (hfToken) {
      console.log("[Try-On] Attempting HF IDM-VTON...");
      try {
        const hfResp = await fetch(
          "https://router.huggingface.co/hf-inference/models/yisol/IDM-VTON",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${hfToken}`,
              "Content-Type": "application/json",
              "x-wait-for-model": "true"
            },
            body: JSON.stringify({
              inputs: {
                background: `data:${baseImg.mimeType};base64,${baseImg.data}`,
                garment: `data:${garmentImg.mimeType};base64,${garmentImg.data}`
              }
            }),
            signal: AbortSignal.timeout(35000)
          }
        );
        if (hfResp.ok) {
          const contentType = hfResp.headers.get("content-type") || "image/png";
          const buf = await hfResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          console.log("[Try-On] HF success!");
          return NextResponse.json({
            result: `data:${contentType};base64,${b64}`,
            engine: "AI Virtual Try-On",
            isFallback: false,
            message: "Your virtual look has been generated by AI."
          });
        }
      } catch (hfErr) {
        console.warn("[Try-On] HF failed:", hfErr);
      }
    }

    // ───── ENGINE B: Gemini Image Editing (True Try-On — keeps YOUR face & body) ─────
    // Two-step: first describe the garment in detail, then edit the user's photo
    if (geminiKey) {
      console.log("[Try-On] Attempting Gemini Image Editing...");
      try {
        // Step 1: describe the garment in precise detail
        const descResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  { text: "Describe this clothing item for an image editor in one sentence: include the exact color, fabric texture, style (e.g. button-down, polo, t-shirt), fit, collar type, and any visible details like pocket or embroidery. Be very specific." },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }]
            }),
            signal: AbortSignal.timeout(12000)
          }
        );

        let garmentDescription = "a casual shirt";
        if (descResp.ok) {
          const descData = await descResp.json();
          garmentDescription = descData.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || garmentDescription;
          console.log("[Try-On] Garment desc:", garmentDescription);
        }

        // Step 2: edit the person's actual photo — keep face, body, pose, background; change ONLY the shirt
        const editPrompt = `Edit this photo: Keep the person's face, hair, body shape, skin tone, pose, and background EXACTLY the same. Replace ONLY the top clothing item (shirt, t-shirt, or top) that the person is wearing with: ${garmentDescription}. Do not change anything else.`;

        const editResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  { text: editPrompt },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } }
                ]
              }],
              generationConfig: { responseModalities: ["IMAGE", "TEXT"] }
            }),
            signal: AbortSignal.timeout(35000)
          }
        );

        if (editResp.ok) {
          const editData = await editResp.json();
          const imgPart = editData.candidates?.[0]?.content?.parts?.find(
            (p: { inlineData?: { data: string; mimeType: string } }) => p.inlineData
          );
          if (imgPart?.inlineData?.data) {
            console.log("[Try-On] Gemini Image Editing success!");
            return NextResponse.json({
              result: `data:${imgPart.inlineData.mimeType || "image/png"};base64,${imgPart.inlineData.data}`,
              engine: "Gemini Image Edit",
              isFallback: false,
              message: `✨ AI Try-On: Your photo with this outfit — ${garmentDescription}`
            });
          }
        } else {
          const errText = await editResp.text().catch(() => "");
          console.warn("[Try-On] Gemini edit failed:", editResp.status, errText.slice(0, 200));
        }
      } catch (gemEditErr) {
        console.warn("[Try-On] Gemini image edit error:", gemEditErr);
      }
    }

    // ───── ENGINE C: Gemini Stylist (Text Analysis Fallback) ─────
    if (geminiKey) {
      console.log("[Try-On] Falling back to Gemini Stylist...");
      try {
        const geminiResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  { text: "In exactly 2 sentences, describe how this exact clothing item would look on this person. Be positive and specific about fit and style." },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }]
            }),
            signal: AbortSignal.timeout(10000)
          }
        );
        if (geminiResp.ok) {
          const gemData = await geminiResp.json();
          const note = gemData.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
          return NextResponse.json({
            result: basePhotoData,
            engine: "Gemini Stylist",
            isFallback: true,
            message: note
              ? `✨ AI Style Analysis: ${note}`
              : "AI engines are busy. Showing your original photo."
          });
        }
      } catch (gemErr) {
        console.warn("[Try-On] Gemini Stylist failed:", gemErr);
      }
    }

    // ───── LAST RESORT FALLBACK ─────
    return NextResponse.json({
      result: basePhotoData,
      engine: "Preview Mode",
      isFallback: true,
      message: "AI engines are warming up. Try again in a moment."
    });

  } catch (err: unknown) {
    console.error("[Try-On] Critical error:", err);
    return NextResponse.json({ error: "Failed to process try-on" }, { status: 500 });
  }
}
