import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { basePhotoData, garmentImageData } = await req.json();
    const hfToken = process.env.HF_API_TOKEN;
    const geminiKey = process.env.GEMINI_API_KEY;

    if (!basePhotoData || !garmentImageData) {
      return NextResponse.json({ error: 'Both person and garment images are required' }, { status: 400 });
    }

    // Helper: extract the raw base64 bytes + mime type from a data URL
    const parseDataUrl = (dataUrl: string) => {
      const match = dataUrl.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/s);
      if (!match) return null;
      return { mimeType: match[1], data: match[2] };
    };

    const baseImg = parseDataUrl(basePhotoData);
    const garmentImg = parseDataUrl(garmentImageData);

    if (!baseImg || !garmentImg) {
      return NextResponse.json({
        result: basePhotoData,
        isFallback: true,
        engine: "Fallback",
        message: "Image data could not be parsed. Showing your original photo."
      });
    }

    // ───── ENGINE A: Hugging Face IDM-VTON (Specialized Try-On) ─────
    if (hfToken) {
      console.log("[Try-On] Attempting Hugging Face IDM-VTON...");
      try {
        const hfResp = await fetch(
          "https://router.huggingface.co/hf-inference/models/yisol/IDM-VTON",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${hfToken}`,
              "Content-Type": "application/json",
              "x-wait-for-model": "true"
            },
            body: JSON.stringify({
              inputs: {
                // Pass inline base64 images directly
                background: `data:${baseImg.mimeType};base64,${baseImg.data}`,
                garment: `data:${garmentImg.mimeType};base64,${garmentImg.data}`
              }
            }),
            signal: AbortSignal.timeout(45000) // 45s timeout
          }
        );

        if (hfResp.ok) {
          const contentType = hfResp.headers.get("content-type") || "image/png";
          const buf = await hfResp.arrayBuffer();
          const b64 = Buffer.from(buf).toString("base64");
          console.log("[Try-On] HF success!");
          return NextResponse.json({
            result: `data:${contentType};base64,${b64}`,
            engine: "AI Virtual Try-On",
            isFallback: false,
            message: "Your virtual look has been generated by AI."
          });
        } else {
          const errText = await hfResp.text().catch(() => "");
          console.warn(`[Try-On] HF failed (${hfResp.status}):`, errText);
        }
      } catch (hfErr) {
        console.warn("[Try-On] HF engine error:", hfErr);
      }
    }

    // ───── ENGINE B: Gemini Vision — Style Analysis Fallback ─────
    // Since full try-on requires specialized models, Gemini provides a thoughtful
    // style description overlaid on the user's own photo
    if (geminiKey) {
      console.log("[Try-On] Attempting Gemini Vision style analysis...");
      try {
        const geminiResp = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              contents: [{
                parts: [
                  {
                    text: "You are a personal fashion stylist. I'll show you a person's photo and a clothing item. In exactly 2 sentences, describe how this outfit would look on this person — mention the fit, color contrast, and overall style impression. Be positive and specific."
                  },
                  { inlineData: { mimeType: baseImg.mimeType, data: baseImg.data } },
                  { inlineData: { mimeType: garmentImg.mimeType, data: garmentImg.data } }
                ]
              }]
            }),
            signal: AbortSignal.timeout(20000)
          }
        );

        if (geminiResp.ok) {
          const gemData = await geminiResp.json();
          const styleNote = gemData.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "";
          console.log("[Try-On] Gemini style note:", styleNote);
          return NextResponse.json({
            result: basePhotoData, // Show person's actual photo
            engine: "Gemini AI Stylist",
            isFallback: true,
            message: styleNote
              ? `✨ AI Fashion Analysis: ${styleNote}`
              : "AI Try-On engines are warming up. Here's your photo — try again in a moment for full virtual try-on."
          });
        } else {
          const errText = await geminiResp.text().catch(() => "");
          console.warn("[Try-On] Gemini failed:", geminiResp.status, errText);
        }
      } catch (gemErr) {
        console.warn("[Try-On] Gemini engine error:", gemErr);
      }
    }

    // ───── FALLBACK: Show user's photo with message ─────
    return NextResponse.json({
      result: basePhotoData,
      engine: "Preview Mode",
      isFallback: true,
      message: "AI try-on engines are currently warming up (free tier). Your photo is shown. Try again shortly for the full virtual look."
    });

  } catch (err: unknown) {
    console.error("[Try-On] Unhandled error:", err);
    const msg = err instanceof Error ? err.message : "Failed to process try-on";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
